### ISSUE TITLE
Allow users to configure ML jobs anytime from Logs  UI

### ISSUE THREAD

**Issue by mukeshelastic** [elastic/logs#20]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Right now the ML job set up is only shown at the beginning and users can not configure ML job to remove any index or disable a data set from an index at later time. This feature will allow users to configure ML jobs any time they want.

**Comment by weltenwort** [comment]
To clarify, we have a "Recreate jobs" button in the log rate and categories result views, that the use can use at any time to go back to the setup form. But the setup is destructive, because it removes the previous job along with its model and results.

This has the advantage that the model is not "polluted" with old data, but the disadvantage that old results are lost.

**Comment by katrin-freihofner** [comment]
I think this will be solved by the [new setup](https://github.com/elastic/logs/issues/14).
